### DISCUSSION TITLE
Functional Docker Compose (with suggestions)

### DISCUSSION THREAD

**Discussion by ezekieldas** [jcorporation/myMPD#1258] [General]
The current Docker Compose example in the [myMPD documentation](https://jcorporation.github.io/myMPD/installation/docker) will not function as shown.

<details>
<summary>docker-compose.yml (current)</summary>

```
---
version: "3.x"
services:
  mympd:
    image: ghcr.io/jcorporation/mympd/mympd
    container_name: mympd
    network_mode: "host"
    user: 1000:1000
    environment:
      - UMASK_SET=022
      - MYMPD_SSL=false
      - MYMPD_HTTP_PORT=8080
    volumes:
      - /path/to/mpd/socket:/run/mpd/socket
      - /path/to/mympd/docker/workdir:/var/lib/mympd/
      - /path/to/mympd/docker/cachedir:/var/cache/mympd/
      - /path/to/music/dir/:/music/:ro
      - /path/to/playlists/dir/:/playlists/:ro
    restart: unless-stopped
```
</details>

Even by omitting `volumes:` the following error will occur:

```
ERROR    mympd     Cache dir: creating "/var/cache/mympd" failed
ERROR    mympd     Permission denied
```

With omitting the `user:` option, the container will then function yet 1) no data or configuration will be persistent 2) the initial run of mympd will be root.

---

For an improved use I've made some minor modifications to aid in quickly getting the container to function and demonstrate some workarounds, shortcomings, and areas to improve.

To use this Compose example, simply create a `./mympd_config` directory with the specified ownership in the same location as the `docker-compose.yml` file. Then start the container and monitor the logs.

```
mkdir ./mympd_config
chown 1000:1000 ./mympd_config
docker compose up -d
docker logs -f mympd
```

<details>
<summary>docker-compose.yml (modified)</summary>

```
services:
  mympd:
    image: ghcr.io/jcorporation/mympd/mympd
    container_name: mympd
    user: 1000:1000
    ##
    ## https://jcorporation.github.io/myMPD/configuration/command-line-options
    ##
    entrypoint: ["/usr/bin/mympd", "-a", "/mympd/mympd_cache", "-w", "/mympd/mympd_workdir"]
    environment:
      - UMASK_SET=022
      - MYMPD_SSL=false
      - MYMPD_HTTP_PORT=8080

      - MPD_HOST=mpd.somewhere.io
      - MPD_PORT=6600
    ports:
      - 8080:8080
    volumes:
      ##
      ## mkdir ./mympd_config ; chown 1000:1000 ./mympd_config
      ##
      - ./mympd_config:/mympd
    restart: unless-stopped
```
</details>

What this does is the following (with suggestions):

- `user:` remains defined as `1000:1000`
   - this could be removed if the current [`RUN adduser` directive](https://github.com/jcorporation/myMPD/blob/8a3a188794bd593266b602924d020b49b22e8d2d/contrib/packaging/docker/Dockerfile.alpine#L16) were modified with uid/gid 1000
- overrides Docker ENTRYPOINT (with `entrypoint:`) to allow for creation of required directories.
  - ultimately this would require a refactor of the mympd codebase to use directories writable by user mympd
  - see also [WORKDIR](https://stackoverflow.com/questions/51066146/what-is-the-point-of-workdir-on-dockerfile) 
- `network_mode: host` is removed in favor of `ports:`
- environment variables `MPD_HOST` and `MPD_PORT` are shown to aid in configuration
