### DISCUSSION TITLE
Small navigation improvements for the Albums view

### DISCUSSION THREAD

**Discussion by edhelas** [jcorporation/myMPD#472] [Ideas]
A few ideas that might improve browsing in the Album view

1) Is it possible to keep the ordering persistent after page reloads (as well as the other parameters like pagination, filtering parameter maybe except the search input and the page), I tend to order my collection in a specific way and I'm loosing the setting each time I reload
2) When clicking on the "Browse Library" button in the main menu, if you are currently viewing an album, would it be possible to go back to the general "album grid" view ?
3) When browsing the albums, keeping the paginate/search bar always visible might help a lot
4) When viewing an album, maybe replacing the "back to album grid" icon with a simple "<" button might be more clear for the user (the button will then always act as a "previous" click if the view is reused elsewhere).

5) Regarding the grid itself, using `justify-content: center` can, at least, give an equal margin on each side of the list.

**Comment by jcorporation** [comment]
I added numbers to your post for easier reference.

1) what you mean exactly with reload? closing and reopening the browser / tab?

2) the button is designed to go the last browse view as default. You can change the behaviour of the button with a custom navbar icon: https://github.com/jcorporation/myMPD/wiki/Custom-navbar-icons

3) I tried this in the past, look at #423 

4) I like the grid button

5) aligend left is for me better than center, aligend with the general margins would be the best. But I found no easy way with bootstrap to achieve this. Eventually bootstrap 5 brings new features for this to work.

**Reply by edhelas** [reply]
Thanks for your replies :) 

Another small CSS fix would be to not use CSS borders but box-shadow instead:

Current code: 
```css
.card-grid:focus, .home-icons:focus {
    border-width: 1px;
    border-style: solid;
    border-color: var(--mympd-highlightcolor, #28a745) !important;
}
```

Suggestion:
```css
.card-grid:focus, .home-icons:focus {
    box-shadow: 0 0 1px 1px var(--mympd-highlightcolor, #28a745);
}
```

This is bringing a similar effect without changing the element size (the current code slightly move the other albums around when clicking on one)
