### ISSUE TITLE
Work and cach folders are being set to root permissions

### ISSUE THREAD

**Issue by bonelifer** [jcorporation/myMPD#1268]
myMPD version: current latest tag

**Describe the bug**
When it creates the work and cache folders, it do so with root permissions instead of the ones in the docker-compose.yml file.

**Expected behavior**
Correct permissions, ie 1000:1000

**Server platform (please complete the following information):**
 - OS: Xubuntu
 - OS version 22.04.4
 -  Platform: x86_64
 - MPD version: 0.23.12

**Client platform (please complete the following information):**
 - Device: Laptop
 - OS: same device

**Configuration (please attach if it can be useful)**

```
services:
  mympd:
    image: ghcr.io/jcorporation/mympd/mympd
    container_name: mympd
    ports:
      - 8081:8080
    user: 1000:1000
    environment:
      - UMASK_SET=022
      - MYMPD_SSL=false
      - MYMPD_HTTP_PORT=8081
    volumes:
      - /run/mpd/socket:/run/mpd/socket
      ## Optional for myGPIOd support
      ## - /run/mygpiod/socket:/run/mygpiod/socket
      - ./data/workdir:/var/lib/mympd/
      - ./data/cachedir:/var/cache/mympd/
      - /media/william/OracleHarbor/LidarMusic/CLEAN/:/var/lib/mpd/music/:ro
      - ../mpd-alsa-docker/data/.mpd/playlists/:/var/lib/mpd/playlists/:ro
    restart: unless-stopped
    network_mode: "host"  # Add host mode networking
```

Manually setting the folder/file permissions fix this (my user/group on host sytstem are 1000:1000):

```
# Set the owner and group to william:william
chown -R william:william "./data"

# Set permissions for owner, group, and others
chmod -R u=rwX,g=rwX,o=rX "./data"
```
