### ISSUE TITLE
myMPD with Docker on arm64 arch

### ISSUE THREAD

**Issue by niawag** [jcorporation/myMPD#333]
Hi and thanks for this promising project. I'm trying to use it with docker (on an arm64 SBC running Coreelec) and am a bit struggling with it. I've managed to pull it from github and created a container with this command:
docker create \
  --name=mympd \
  -p 80:80 \
  -v /storage/mnt/multimedia/mp3/:/usr/share/mympd/htdocs/library/:ro \
  -v mympd:/etc/mympd/ \
  --restart unless-stopped \
  docker.pkg.github.com/jcorporation/mympd/mympd:latest

I can start it but it keeps restarting with this error in the logs: 
standard_init_linux.go:211: exec user process caused "exec format error"

I'm pretty sure it's a docker create configuration problem but I wasn't able to find documentation on how to proceed except some from @rollenwiese (here: https://github.com/jcorporation/myMPD/issues/85).

Does someone know how to run this with Docker?

**Comment by jcorporation** [comment]
The docker container is only for x86 architecture

**Comment by niawag** [comment]
Ok, thanks for your answer! Do you plan to create a docker image for arm64 too? I'd be willing to try it out and debug if necessary.

I've also found this image: https://hub.docker.com/r/tras2/mympd but there is not much help to use it, if I manage to do so I'll report it here if others want to run myMPD on an arm64 based SBC

**Comment by Tras2** [comment]
Hi @niawag 

I got your email - i'll reply here if that's ok.

For clarity, the image I uploaded to dockerhub is running on a Raspberry Pi 3 Model B Rev 1.2 running Ubuntu 20.04 x64.  As you might be able to see from the image layer I build mympd from source and the build is done on the RPi itself before being push to dockerhub.

As for running it, i use this `docker-compose.yml` file:-
```
  jukebox-mympd:
    container_name: jukebox-mympd
    image: tras2/mympd
    ports:
      - "443:443"
    networks:
      - mpd
    volumes:
      - ./mympd.conf:/etc/mympd.conf
      - mympd-state:/var/lib/mympd/state/
    restart: always
    depends_on:
      - jukebox-mpd

```

I have mpd running in another container (`jukebox-mpd`) which is also on the `mpd` network.  The `mympd.conf` configurations is like this:-
```
[mpd]
#Connection to mpd, unix socket or host/port, socket preferred
host = jukebox-mpd
port = 6600
```


I'm still at the start of my learning journey with containers (& linux in general!), but I'll try and help on this if/when I can.

(As an aside, I made a mistake with installing Ubuntu x64 on this Pi - when i get an evening spare i'll be re-installing with Raspbian x86 to make it consistant with the other Pi's in my house)
