### ISSUE TITLE
[Docker] Initial setup not working and SSL issues  

### ISSUE THREAD

**Issue by Hajuskin** [jcorporation/myMPD#675]
myMPD version: 9.1.0

**Describe the bug**

I updated my Pi to Raspbian buster 64bit and installed a clean new image of myMPD using this docker compose:

```
services:
  mympd:
    image: ghcr.io/jcorporation/mympd/mympd
    container_name: mympd
    network_mode: "host"
    environment:
      - TZ=Europe/Berlin
      - UMASK_SET=022 #optional
      - MYMPD_SSL=false
      - MYMPD_SSL_PORT=8082
      - MYMPD_LOGLEVEL=7
    volumes:
      - /run/mpd/socket:/run/mpd/socket #optional, use if you connect to mpd using sockets
      - ./volumes/mympd:/var/lib/mympd/
      - /home/pi/Music/:/music/:ro
      - /home/pi/Music/Playlists Raspi/:/playlists/:rw
    restart: unless-stopped
```
I expected that myMPD would use these enviroment variables as initial values, but the configuration files contains the default values (eg. ssl_port = 443 and loglevel = 5)
Not sure if related and/or intended, but I noticed that the config folder in `var/lib/mympd` is owned by `root`, while all other folders are owned by `mympd`.

Beside that I can reach myMPD on port 443 and mpd is connected on `/run/mpd/socket`. My real problem starts when I change the ssl-port by editing the `ssl_port` config file. After restarting myMPD I can access the frontend on the new port, but now I get these notifications: `Websocket is disconnected` and `Websocket connection failed, trying to reconnect`
As the log shows repeated `certificate unknown` messages I downloaded the CA certificate and imported it into chrome, but it makes no difference (and I still get ssl warnings in chome).

**Server plattform (please complete the following information):**
 - myMPD running in docker
 - OS: raspberrypi os
 - OS version: 5.10.92-v8+
 - Plattform: aarch64
 - MPD version: 0.23.5

**Debug logs (please attach if it can be usefull)**
[mympd_logs.txt](https://github.com/jcorporation/myMPD/files/8017205/mympd_logs.txt)
[mpd.log](https://github.com/jcorporation/myMPD/files/8017207/mpd.log)

 
**Configuration (please attach if it can be usefull)**
[mympd_state.tar.gz](https://github.com/jcorporation/myMPD/files/8017367/mympd_state.tar.gz)
[mympd_config.tar.gz](https://github.com/jcorporation/myMPD/files/8017369/mympd_config.tar.gz)
[mpd.conf.gz](https://github.com/jcorporation/myMPD/files/8017396/mpd.conf.gz)
