### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by rollenwiese** [jcorporation/myMPD#85]
Thanks for your work on this nice, lean MPD client.

Not sure if you have any interest in adding a Dockerfile to your repository? Could be a first step towards an automated push of an image over to Docker hub.

I've created one going about as far as I can go without making minor modifications to your install scripts.

https://gitlab.com/rollenwiese/mympd-tracking/blob/docker-build/Dockerfile

Build log: https://gitlab.com/rollenwiese/mympd-tracking/-/jobs/143164751

It's a multi-stage build resulting in a ~90MB Debian 9 (slim) based image with libmpdclient 2.17 (master) and myMPD (4.7.2). 

The minify steps aren't included but are trivial to add.

I re-use your debian/postinst script which works fine.

The MPDHOST/MPDPORT/SSL configuration options are externalized and can be set in a docker-compose file, or specified on the docker command line.

The the certificates are still created by your _crcert.sh_ script but are non-functional. To be more docker friendly, the call to the creation script would have to be moved out of the _postinst_ script into and the script called at the 'ENTRYPOINT' in the Dockerfile. This way they are generated when the container starts rather than when the Docker image is created.

Additionally for the SSL certs to be useful the hostname or ip address used in your certificate script would need an additional environment variable(s) added for use with the CN/subjectAltName items of the open ssl configuration. Like MPDHOST, etc these variables could be externalized and (optionally) passed into the container when it's initialized.

I'll add though that it's likely most people who would run this in a container probably are already running behind a reverse proxy / SSL endpoint, so maybe not too relevant.

To sample, drop the linked Dockerfile into a clone of your repo then run:
```shell
docker build -t mympd .
docker run -e "MYMPD_MPDHOST=127.0.0.1" -e "MYMPD_SSL=false" -p 39999:80 -it mympd
```
http://localhost:39999/

Omitting the environment variables just uses your defaults.

Anyway, happy to contribute towards this if you're interested. If not that's cool too.

**Comment by rollenwiese** [comment]
`
docker build -t mympd .

docker run -e "MYMPD_MPDHOST=xxx.xxx.xxx.xxx" -e "MYMPD_SSL=false" -it mympd
`

**Comment by rollenwiese** [comment]
I was able to work through the SSL issue. The only qualification is that the SSL certs must be stored in a volume or they will be regenerated every time the container is recreated. This would be true for many SSL enabled web applications running in a docker environment.

https://github.com/rollenwiese/myMPD/commit/f0bb77e5b3c55a09f4d6079666d6c61276bd9ae0

The remaining issue is the minification script, which perhaps isn't essential, but nice to have.

For it to work the minify scripting would have to be pulled out of mkrelease and placed into it's own script that may be called by either mkrelease.sh or the Dockerfile.

I've done this (not commited to repository), but there's an issue with the 'newer than' comparisons exiting with a non-zero exit code, causing the docker build to fail. This could be dealt with by either rewriting those conditionals as if/then blocks, or forcing a mkrelease-minify.sh script to exit with a 0 exit code whether any minification occured or not. Acceptable but a little hack-ish maybe.

Otherwise the above reference commit works fine. It would work with a docker-compose file something like this: (traefik reverse proxy settings in comments)

```yaml
version: '3'

services:
  mympd:
    container_name: mympd
    environment:
      MYMPD_MPDHOST: 192.168.9.2
      MYMPD_MPDPORT: 6600
      MYMPD_SSL: true
      MYMPD_COVERIMAGENAME: cover.jpg
      MYMPD_LOGLEVEL: 2
    image: mympd:latest
#    labels:
#      - "traefik.enable=true"
#      - "traefik.backend=mympd"
#      - "traefik.frontend.rule=Host:mympd.example.net"
#      - "traefik.frontend.whiteList.sourceRange=192.168.9.0/24"
#      - "traefik.port=80"
#      - "traefik.docker.network=traefik"
    networks:
      - mympd
#      - traefik
    ports:
      - "40000:80"
      - "40001:443"
    restart: always
    volumes:
      - /mnt/multimedia/audio/music/:/usr/share/mympd/htdocs/library/:ro
      - mympd_certs:/etc/mympd/ssl

networks:

  mympd:

#  traefik:
#    external:
#      name: traefik

volumes:

  mympd_certs:

```

**Comment by jcorporation** [comment]
The minification is not necessary. I distribute minified files in the release tarballs.

**Comment by jcorporation** [comment]
```I've done this (not commited to repository), but there's an issue with the 'newer than' comparisons exiting with a non-zero exit code, causing the docker build to fail. This could be dealt with by either rewriting those conditionals as if/then blocks, or forcing a mkrelease-minify.sh script to exit with a 0 exit code whether any minification occured or not. Acceptable but a little hack-ish maybe.```

In the decoupling branch the mkrelease.sh script is rewritten. Can you test your docker build with this branch? This branch will be shortly merged in the master branch for the 5.0.0 release of myMPD.

**Comment by rollenwiese** [comment]
Hey no problem, will go through this in the next day or so. I don't anticipate an issue, except I may need to add an environment variable to mkrelease the indicates whether the mkrelease.sh script is being called within a container build vs non-container, and wrap the actual compilation command inside a block that's only called if not inside a container. If two days is too long, no problem, can always merge against a later version.

**Comment by jcorporation** [comment]
Your pull request #88 is now merged and I am testing it in my environment and at the opensuse buildservice.

**Comment by jcorporation** [comment]
One question: Why do you not use ```/etc/mympd/``` as a volume? Shouldn't this make the environment variables obsolet?

**Comment by jcorporation** [comment]
Because the volume is anyway needed for ssl it would be the better and easier way. 

Your approach can be alongside implemented. I have the first working code for reading environment variables and overwriting the configuration file. I would fine tune and extend the code to read all configuration options from environment.

myMPD 5.0.0 is on the way (the extra branch was merged into devel). It would be great, if this versions has docker support integrated.

The docker-compose file wasn't integrated in your pull  request. I am unfamiliar with docker, does the user need this file?

**Comment by rollenwiese** [comment]
Thanks for working on pulling in environment variables, much appreciated. The docker compose files are usually created by the end user, but I have seen other applications provide simple examples like the one above as a reference. I think the above one is fine, just need to change /etc/mympd to a volume and comment out the 'environment' block. I guess it could just be dropped into contrib/docker?

**Comment by rollenwiese** [comment]
Something like this maybe, can be changed however you like:
```yaml
version: '3'

services:
  mympd:
    container_name: mympd
#    environment:
#      MYMPD_MPDHOST: 192.168.9.2
#      MYMPD_MPDPORT: 6600
#      MYMPD_SSL: true
#      MYMPD_COVERIMAGENAME: cover.jpg
#      MYMPD_LOGLEVEL: 2
#    image: mympd:latest
    build: $MYMPD_BUILD_PATH    
#    labels:
#      - "traefik.enable=true"
#      - "traefik.backend=mympd"
#      - "traefik.frontend.rule=Host:mympd.example.net"
#      - "traefik.frontend.whiteList.sourceRange=192.168.9.0/24"
#      - "traefik.port=80"
#      - "traefik.docker.network=traefik"
    networks:
      - mympd
#      - traefik
    ports:
      - "40000:80"
      - "40001:443"
    restart: always
    volumes:
      - /mnt/multimedia/audio/music/:/usr/share/mympd/htdocs/library/:ro
      - mympd:/etc/mympd/

networks:

  mympd:

#  traefik:
#    external:
#      name: traefik

volumes:

  mympd:

```
