### ISSUE TITLE
Run as specific user in docker

### ISSUE THREAD

**Issue by PierreRust** [jcorporation/myMPD#968]
### Discussed in https://github.com/jcorporation/myMPD/discussions/967

<div type='discussions-op-text'>

<sup>Originally posted by **PierreRust** February  7, 2023</sup>
Hi,

I'm playing with myMPD and it's a great mpd web client , the best I've seen so far, thanks for your work !

I'm running it as part of a docker compose stack, where all containers are run as a specific user (to make conf file management & backup easier).
When running myMPD, it automatically switches to the myMPD user, which is created in the [Dockerfile](https://github.com/jcorporation/myMPD/blob/master/contrib/packaging/docker/Dockerfile.alpine). However, that user uid and guid does not match the user I'm using everywhere else, which causes issues.

I've seen that the use of xUID, which is the standard way of dealing with that in docker to run as non-root inside the container,  was mentioned in the documentation at some point, and them [removed](https://github.com/jcorporation/myMPD/commit/4f0b27ec2b2c2d8b4c2c238ee8ef2bcc94af83ea). On the other hand, from what I see in the dockerfile history, these env. variables were never actually used.
Am I missing something of is there any reason for that situation ?

I'd love to be able to set the user and group id to be used inside the container. This would only require to change the dockerfile (and the documentation accordingly),  I can contribute a PR for that if you want.</div>

**Comment by jcorporation** [comment]
myMPD switches the user itself if it started with uid 0. Does this help?

https://jcorporation.github.io/myMPD/configuration/command-line-options

**Comment by PierreRust** [comment]
Hi,

you've been faster than me ! 

From what I see there are several ways to implement this :

* the one you used in your commit. It fixes my issue but might be considered as not entirely "clean" as  the entrypoint still run as root in the container. Besides it seems that it will run `addgroup` and `adduser` every time we start the container.
* use (docker) ARG for UID and GUID when building the container. However as these args only work at build time, that makes the docker-compose file more complex as we need to rebuild the container before running it.
* use the `user: <uid>:<guid>` directive in the docker-compose file. With this approach we don't need to change anything in the Dockerfile, but need to add an additional volume for the cache directory (as the mympd would not have the roghts inside the container. I'm using the following in my dockerfile and it works perfectly : 

```
   [...]
    user: 1001:1001
    volumes:
      - /hosting/myMPD/:/var/lib/mympd/
      - /hosting/myMPD/:/var/cache/mympd
      - /data/Music/:/music/:ro
      - /data/Music/Playlists:/playlists/:ro      
    restart: unless-stopped
```

**Comment by jcorporation** [comment]
> use the user: <uid>:<guid> directive in the docker-compose file

I think this is the best approach.

**Comment by jcorporation** [comment]
Changed to the user directive, please test.

**Comment by PierreRust** [comment]
works great ! :+1:

**Comment by jcorporation** [comment]
Right, I added this to the example docker compose file.

**Comment by PierreRust** [comment]
great, thanks ! :+1:

**Comment by mishka81** [comment]
Hello,
On my Raspberry Pi running the latest image with the "pi" user (uid + gid 1000), I have this error :
```
mympd  | NOTICE   mympd     Cache dir: "/var/cache/mympd"
mympd  | NOTICE   mympd     Work dir: "/var/lib/mympd"
mympd  | ERROR    mympd     Config dir: creating "/var/lib/mympd/config" failed
mympd  | ERROR    mympd     File exists
mympd  | Exiting erroneous, thank you for using myMPD
mympd exited with code 1
```
Here is my docker-compose :
```
---
version: "3.1"
services:
  mympd:
    image: ghcr.io/jcorporation/mympd/mympd
    container_name: mympd
    network_mode: "host"
    user: 1000:1000
    environment:
      - UMASK_SET=022
      - MYMPD_SSL=false
      - MYMPD_HTTP_PORT=8080
    volumes:
      - ~/.mpd/socket:/run/mpd/socket
      - ./volumes/mympd/work:/var/lib/mympd
      - ./volumes/mympd/cache:/var/cache/mympd
      - /media/pi/NAS/music/library:/music/:ro
      - ~/.mpd/playlists:/playlists/:ro
    restart: unless-stopped
```

Any ideas ?

Thx !
